### ISSUE TITLE
Version 1: Parse JSON

### ISSUE THREAD

**Issue by abhiyerra** [abhiyerra/goconfigure#3]
Need to parse JSON.
## Stage 1
- [x] Initially just have a method of parsing json directly.
- [x] Need to handle nested JSON objects.

These two methods would just be using the default encoding/json library to parse the input necessary.
## Stage 2
- [ ] Select a file to be read and parsed.
- [ ] Need to convert file according to goconfigure tag. Rewrite the structs to include the json tag. These tags are what will be used to convert the json objects.
